drop table items;
drop table users;
create TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(512) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

create TABLE IF NOT EXISTS items ( id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
 name VARCHAR(100),
 description VARCHAR(500),
 available Boolean
 owner BIGINT,
 equest BIGINT,
 CONSTRAINT fk_items_to_users FOREIGN KEY(owner) REFERENCES users(id),
 UNIQUE(id, url)
 );

